# Default values for big-dipper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: forbole/big-dipper-2.0-cosmos
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
affinity: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: chain.bigdipper.live
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
   - secretName: letsencrypt-secret-bigdipper-2.0
     hosts:
       - chain.bigdipper.live